### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Polyg0n** [Polyg0n/oblib#4]
- [ ] Complete CPU ID and Memory allocation
- [ ] Create simple Disk creation and I/O
- [ ] Create page system
- [ ] Write memsense
- [ ] Create virtual disk
- [ ] Implement GRUB (and maybe Linux Kernel?)
